name: After Maven
description: Runs after_maven.sh using xsltproc and count.xslt
runs:
  using: "composite"
  steps:
    - name: Install xsltproc (Linux)
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y xsltproc
      shell: bash
    - name: Install xsltproc (macOS)
      if: runner.os == 'macOS'
      run: brew install xsltproc
      shell: bash
    - name: Install xsltproc (Windows)
      if: runner.os == 'Windows'
      run: choco install xsltproc
      shell: pwsh
    - name: Make after_maven.sh executable
      run: chmod +x ${{ github.action_path }}/after_maven.sh
      shell: bash
    - name: Run after_maven.sh
      run: ${{ github.action_path }}/after_maven.sh
      shell: bash