name: After Maven
description: Runs after_maven.sh using xsltproc and count.xslt
runs:
  using: "composite"
  steps:
    - name: Normalize action path
      id: norm_path
      run: echo "norm_path=${GITHUB_ACTION_PATH//\\//}" >> $GITHUB_OUTPUT
      shell: bash
    - name: Install xsltproc (Linux)
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y xsltproc
      shell: bash
    - name: Install xsltproc (macOS)
      if: runner.os == 'macOS'
      run: >
        brew install libxslt bash
        echo $(brew --prefix)/bin/bash | sudo tee -a /etc/shells
        chsh -s $(brew --prefix)/bin/bash
      shell: bash
    - name: Install xsltproc (Windows)
      if: runner.os == 'Windows'
      run: choco install xsltproc
      shell: pwsh
    - name: Make after_maven.sh executable
      run: chmod +x ${{ steps.norm_path.outputs.norm_path }}/after_maven.sh
      shell: bash
    - name: Run after_maven.sh
      run: ${{ steps.norm_path.outputs.norm_path }}/after_maven.sh
      shell: bash