---
name: After Maven
description: Runs after_maven.sh using xsltproc and count.xslt
branding:
  icon: 'alert-circle'
  color: 'blue'
runs:
  using: "node20"
  main: 'dist/index.js'

inputs:
  determin_version:
    description: 'get the version from the main pom.xml, and show that too'
    required: false
    default: 'true'
